In [270]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from tensorflow.keras.models import Sequential,load_model
from tensorflow.keras.layers import Dense
from keras.utils import to_categorical

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/cifar1001/data_batch_1


In [271]:
dic = pd.read_pickle('/kaggle/input/cifar1001/data_batch_1')

In [272]:
dic.keys()

dict_keys([b'batch_label', b'labels', b'data', b'filenames'])

In [273]:
scaler = MinMaxScaler()

In [274]:
X = scaler.fit_transform(np.array(list(dic[b'data'])))
y = np.array(list(dic[b'labels']))
y = to_categorical(y)

In [275]:
y.shape

(10000, 10)

In [276]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size = .2,random_state = 42)

In [277]:
x_train.shape

(8000, 1024)

In [278]:
model = Sequential()
model.add(Dense(units = 8,activation = 'sigmoid' , input_dim = X.shape[1]))
model.add(Dense(units = 16 , activation = 'sigmoid'))
model.add(Dense(units = 32 , activation = 'sigmoid'))
model.add(Dense(units = 64 , activation = 'sigmoid'))
model.add(Dense(units = 128 , activation = 'sigmoid'))
model.add(Dense(units = 10 , activation = 'softmax'))

In [279]:
model.compile(loss = 'categorical_crossentropy' , optimizer = 'sgd' , metrics = ['accuracy'])

In [280]:
y_train.shape

(8000, 10)

In [281]:
model.fit(x_train,y_train,epochs = 500, batch_size = 100 )

Epoch 1/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3477 - accuracy: 0.0980
Epoch 2/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1035
Epoch 3/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1002
Epoch 4/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1013
Epoch 5/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1016
Epoch 6/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.0991
Epoch 7/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1009
Epoch 8/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.1032
Epoch 9/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3036 - accuracy: 0.0966
Epoch 10/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1025
Epoch 11/

80/80 [==============================] - 0s 2ms/step - loss: 2.3036 - accuracy: 0.0970
Epoch 84/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1014
Epoch 85/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1018
Epoch 86/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3035 - accuracy: 0.0988
Epoch 87/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1065
Epoch 88/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.0971
Epoch 89/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.0997
Epoch 90/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3030 - accuracy: 0.1030
Epoch 91/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3029 - accuracy: 0.1066
Epoch 92/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1013
Epoch 93/500


80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1036
Epoch 165/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1018
Epoch 166/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1013
Epoch 167/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.0999
Epoch 168/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.0996
Epoch 169/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3029 - accuracy: 0.1018
Epoch 170/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1026
Epoch 171/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3035 - accuracy: 0.0995
Epoch 172/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1020
Epoch 173/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.1032
Epoc

80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1020
Epoch 246/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.1014
Epoch 247/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3035 - accuracy: 0.0970
Epoch 248/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.0966
Epoch 249/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3030 - accuracy: 0.1045
Epoch 250/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.0948
Epoch 251/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1018
Epoch 252/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.0990
Epoch 253/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1039
Epoch 254/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1058
Epoc

80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.0995
Epoch 327/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.0986
Epoch 328/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.0974
Epoch 329/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3028 - accuracy: 0.1014
Epoch 330/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1002
Epoch 331/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1021
Epoch 332/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1014
Epoch 333/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1025
Epoch 334/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1011
Epoch 335/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.0989
Epoc

80/80 [==============================] - 0s 2ms/step - loss: 2.3035 - accuracy: 0.1013
Epoch 408/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.0988
Epoch 409/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3030 - accuracy: 0.1026
Epoch 410/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.0994
Epoch 411/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.0990
Epoch 412/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1023
Epoch 413/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3029 - accuracy: 0.0966
Epoch 414/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.0948
Epoch 415/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3030 - accuracy: 0.1041
Epoch 416/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1056
Epoc

80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.0978
Epoch 488/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3029 - accuracy: 0.1051
Epoch 489/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.1025
Epoch 490/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3033 - accuracy: 0.1039
Epoch 491/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3031 - accuracy: 0.1029
Epoch 492/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3032 - accuracy: 0.1046
Epoch 493/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1014
Epoch 494/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3030 - accuracy: 0.1029
Epoch 495/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3030 - accuracy: 0.1036
Epoch 496/500
80/80 [==============================] - 0s 2ms/step - loss: 2.3034 - accuracy: 0.1007
Epoc

In [282]:
y_pred = model.predict(x_test)


In [283]:
y_pred

array([[0.09881298, 0.09618416, 0.10975742, ..., 0.09922498, 0.10329238,
        0.09830736],
       [0.09883481, 0.09621572, 0.10973343, ..., 0.09918845, 0.10331707,
        0.09831426],
       [0.0988389 , 0.09621779, 0.1097047 , ..., 0.09919725, 0.10333497,
        0.09832861],
       ...,
       [0.0988529 , 0.09620359, 0.1097078 , ..., 0.09922316, 0.10332394,
        0.09829709],
       [0.09880678, 0.09618884, 0.10976424, ..., 0.09920441, 0.10330294,
        0.09830511],
       [0.0988281 , 0.09619542, 0.10973917, ..., 0.09920164, 0.10333491,
        0.09830774]], dtype=float32)

In [292]:
for i in y_pred:
    print(list(i).index(max(list(i))))

(array([0.09881298, 0.09618416, 0.10975742, 0.10002542, 0.09637225,
        0.09511302, 0.10291008, 0.09922498, 0.10329238, 0.09830736],
       dtype=float32),
 array([0.09883481, 0.09621572, 0.10973343, 0.10000722, 0.09637746,
        0.09511276, 0.10289875, 0.09918845, 0.10331707, 0.09831426],
       dtype=float32))